// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: qymwhqhvboypctpdocrw

class SupabaseConfig {
  static const String supabaseUrl = 'https://qymwhqhvboypctpdocrw.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5bXdocWh2Ym95cGN0cGRvY3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NTcwMjcsImV4cCI6MjA3NzEzMzAyN30.mgwtBtZtP1s2Gu1yyNI7Z9P08C5N_Fhux2JlmLdyAAU';
}
